/**
 * @file mockData.ts
 * @description Realistic seed-compliant mock dataset for Store Inventory (/inventory).
 * Aligned with Docs/06_seed-data-spec.md and Docs/04_database-schema-v4.md.
 */

import { Store, StockItem, InventoryTransaction, ArrivedTrainBooking } from './types';

/**
 * Baseline list of destination stores across the distribution network.
 * Primary default: Kandy Central, matching UI/store_inventory/screen.png and Docs/06_seed-data-spec.md.
 */
export const MOCK_STORES: Store[] = [
  { store_id: 1, store_name: 'Kandy Central', city_id: 1, city_name: 'Kandy' },
  { store_id: 2, store_name: 'North Branch', city_id: 2, city_name: 'Colombo' },
  { store_id: 3, store_name: 'East Depot', city_id: 7, city_name: 'Trincomalee' },
  { store_id: 4, store_name: 'Colombo Station Store', city_id: 2, city_name: 'Colombo' },
  { store_id: 5, store_name: 'Galle Station Store', city_id: 4, city_name: 'Galle' },
  { store_id: 6, store_name: 'Jaffna Station Store', city_id: 6, city_name: 'Jaffna' },
];

/**
 * Baseline inventory stock matching UI/store_inventory/screen.png for Store 1 (Kandy Central).
 */
export const INITIAL_MOCK_STOCK: Record<number, StockItem[]> = {
  1: [
    {
      product_id: 1,
      product_name: 'Premium Chocolate Bars',
      sku: 'CHOC-PR-100',
      category: 'Confectionery',
      unit_of_measure: 'bars',
      quantity_on_hand: 4500,
      threshold: 1000,
      updated_at: 'Today, 08:30 AM',
      status: 'healthy',
    },
    {
      product_id: 2,
      product_name: 'Gummy Bears (Bulk)',
      sku: 'GUM-BLK-50',
      category: 'Confectionery',
      unit_of_measure: 'packs',
      quantity_on_hand: 120,
      threshold: 300,
      updated_at: 'Yesterday, 14:15 PM',
      status: 'low_stock',
    },
    {
      product_id: 3,
      product_name: 'Caramel Chews',
      sku: 'CAR-CHW-250',
      category: 'Confectionery',
      unit_of_measure: 'packs',
      quantity_on_hand: 8200,
      threshold: 1000,
      updated_at: 'Oct 24, 09:45 AM',
      status: 'healthy',
    },
    {
      product_id: 4,
      product_name: 'Hard Candies Assortment',
      sku: 'HRD-AST-500',
      category: 'Confectionery',
      unit_of_measure: 'packs',
      quantity_on_hand: 12050,
      threshold: 2000,
      updated_at: 'Oct 23, 16:20 PM',
      status: 'healthy',
    },
    {
      product_id: 5,
      product_name: 'Mint Tins',
      sku: 'MNT-TIN-100',
      category: 'Confectionery',
      unit_of_measure: 'tins',
      quantity_on_hand: 45,
      threshold: 200,
      updated_at: 'Today, 10:05 AM',
      status: 'critical',
    },
    {
      product_id: 6,
      product_name: 'Detergent Powder 1kg',
      sku: 'DET-POW-1KG',
      category: 'Household',
      unit_of_measure: 'box',
      quantity_on_hand: 3400,
      threshold: 500,
      updated_at: 'Oct 22, 11:15 AM',
      status: 'healthy',
    },
    {
      product_id: 7,
      product_name: 'Tea Powder 400g',
      sku: 'TEA-POW-400G',
      category: 'Food',
      unit_of_measure: 'pack',
      quantity_on_hand: 2800,
      threshold: 300,
      updated_at: 'Oct 21, 14:00 PM',
      status: 'healthy',
    },
    {
      product_id: 8,
      product_name: 'Rice 5kg Bag',
      sku: 'RIC-5KG-BAG',
      category: 'Food',
      unit_of_measure: 'bag',
      quantity_on_hand: 1950,
      threshold: 250,
      updated_at: 'Oct 20, 10:20 AM',
      status: 'healthy',
    },
  ],
  2: [
    {
      product_id: 1,
      product_name: 'Detergent Powder 1kg',
      sku: 'DET-POW-1KG',
      category: 'Household',
      unit_of_measure: 'box',
      quantity_on_hand: 1800,
      threshold: 300,
      updated_at: 'Today, 09:10 AM',
      status: 'healthy',
    },
    {
      product_id: 3,
      product_name: 'Biscuits Family Pack',
      sku: 'BIS-FAM-PCK',
      category: 'Food',
      unit_of_measure: 'pack',
      quantity_on_hand: 3400,
      threshold: 500,
      updated_at: 'Yesterday, 11:20 AM',
      status: 'healthy',
    },
    {
      product_id: 5,
      product_name: 'Tea Powder 400g',
      sku: 'TEA-POW-400G',
      category: 'Food',
      unit_of_measure: 'pack',
      quantity_on_hand: 85,
      threshold: 150,
      updated_at: 'Today, 10:00 AM',
      status: 'low_stock',
    },
    {
      product_id: 7,
      product_name: 'Rice 5kg Bag',
      sku: 'RIC-5KG-BAG',
      category: 'Food',
      unit_of_measure: 'bag',
      quantity_on_hand: 2100,
      threshold: 400,
      updated_at: 'Oct 24, 16:30 PM',
      status: 'healthy',
    },
  ],
  3: [
    {
      product_id: 1,
      product_name: 'Detergent Powder 1kg',
      sku: 'DET-POW-1KG',
      category: 'Household',
      unit_of_measure: 'box',
      quantity_on_hand: 2200,
      threshold: 400,
      updated_at: 'Today, 11:00 AM',
      status: 'healthy',
    },
    {
      product_id: 2,
      product_name: 'Dish Soap 500ml',
      sku: 'DSH-SOP-500ML',
      category: 'Household',
      unit_of_measure: 'bottle',
      quantity_on_hand: 40,
      threshold: 200,
      updated_at: 'Today, 08:15 AM',
      status: 'critical',
    },
    {
      product_id: 4,
      product_name: 'Instant Noodles Box (24)',
      sku: 'NDL-BOX-24',
      category: 'Food',
      unit_of_measure: 'box',
      quantity_on_hand: 4500,
      threshold: 500,
      updated_at: 'Oct 23, 14:10 PM',
      status: 'healthy',
    },
  ],
};

/**
 * Arrived train bookings with pending goods awaiting receipt at destination stores.
 */
export const MOCK_ARRIVED_TRAIN_BOOKINGS: Record<number, ArrivedTrainBooking[]> = {
  1: [
    {
      train_booking_id: 101,
      trip_code: 'TRIP-CMB-2026-088',
      origin_city: 'Kandy',
      destination_city: 'Colombo',
      arrival_datetime: 'Today, 06:45 AM',
      items: [
        { product_id: 1, product_name: 'Detergent Powder 1kg', sku: 'DET-POW-1KG', expected_quantity: 1200 },
        { product_id: 2, product_name: 'Dish Soap 500ml', sku: 'DSH-SOP-500ML', expected_quantity: 600 },
        { product_id: 5, product_name: 'Tea Powder 400g', sku: 'TEA-POW-400G', expected_quantity: 450 },
        { product_id: 8, product_name: 'Toothpaste 100g', sku: 'TP-100G-TUBE', expected_quantity: 500 },
      ],
    },
    {
      train_booking_id: 102,
      trip_code: 'TRIP-CMB-2026-089',
      origin_city: 'Kandy',
      destination_city: 'Colombo',
      arrival_datetime: 'Yesterday, 19:30 PM',
      items: [
        { product_id: 3, product_name: 'Biscuits Family Pack', sku: 'BIS-FAM-PCK', expected_quantity: 2000 },
        { product_id: 4, product_name: 'Instant Noodles Box (24)', sku: 'NDL-BOX-24', expected_quantity: 1500 },
        { product_id: 7, product_name: 'Rice 5kg Bag', sku: 'RIC-5KG-BAG', expected_quantity: 1000 },
      ],
    },
  ],
  2: [
    {
      train_booking_id: 201,
      trip_code: 'TRIP-NEG-2026-041',
      origin_city: 'Kandy',
      destination_city: 'Negombo',
      arrival_datetime: 'Today, 07:15 AM',
      items: [
        { product_id: 1, product_name: 'Detergent Powder 1kg', sku: 'DET-POW-1KG', expected_quantity: 500 },
        { product_id: 5, product_name: 'Tea Powder 400g', sku: 'TEA-POW-400G', expected_quantity: 250 },
      ],
    },
  ],
  3: [
    {
      train_booking_id: 301,
      trip_code: 'TRIP-GAL-2026-033',
      origin_city: 'Kandy',
      destination_city: 'Galle',
      arrival_datetime: 'Today, 08:30 AM',
      items: [
        { product_id: 2, product_name: 'Dish Soap 500ml', sku: 'DSH-SOP-500ML', expected_quantity: 400 },
        { product_id: 4, product_name: 'Instant Noodles Box (24)', sku: 'NDL-BOX-24', expected_quantity: 800 },
      ],
    },
  ],
};

/**
 * Initial historical ledger transactions for store inventory movements.
 */
export const INITIAL_MOCK_TRANSACTIONS: InventoryTransaction[] = [
  {
    transaction_id: 5001,
    store_id: 1,
    store_name: 'Colombo Station Store',
    product_id: 1,
    product_name: 'Detergent Powder 1kg',
    sku: 'DET-POW-1KG',
    change_qty: 1500,
    transaction_type: 'receive',
    reference_code: 'TB-102',
    created_at: '2026-08-31 08:30:15',
    created_by_name: 'Operator Silva',
    notes: 'Arrived on Express Cargo 401 on schedule',
  },
  {
    transaction_id: 5002,
    store_id: 1,
    store_name: 'Colombo Station Store',
    product_id: 7,
    product_name: 'Rice 5kg Bag',
    sku: 'RIC-5KG-BAG',
    change_qty: -350,
    transaction_type: 'dispatch',
    reference_code: 'DEL-8801',
    created_at: '2026-08-31 07:45:00',
    created_by_name: 'Driver Perera (NB-1001)',
    notes: 'Loaded for Colombo North Route delivery',
  },
  {
    transaction_id: 5003,
    store_id: 1,
    store_name: 'Colombo Station Store',
    product_id: 2,
    product_name: 'Dish Soap 500ml',
    sku: 'DSH-SOP-500ML',
    change_qty: -200,
    transaction_type: 'dispatch',
    reference_code: 'DEL-8802',
    created_at: '2026-08-30 14:15:30',
    created_by_name: 'Driver Fernando (NB-1002)',
    notes: 'Colombo South Wholesale distribution',
  },
  {
    transaction_id: 5004,
    store_id: 1,
    store_name: 'Colombo Station Store',
    product_id: 3,
    product_name: 'Biscuits Family Pack',
    sku: 'BIS-FAM-PCK',
    change_qty: 2500,
    transaction_type: 'receive',
    reference_code: 'TB-098',
    created_at: '2026-08-30 09:45:00',
    created_by_name: 'Operator Silva',
    notes: 'Batch inspected and verified',
  },
  {
    transaction_id: 5005,
    store_id: 1,
    store_name: 'Colombo Station Store',
    product_id: 5,
    product_name: 'Tea Powder 400g',
    sku: 'TEA-POW-400G',
    change_qty: -5,
    transaction_type: 'adjustment',
    reference_code: 'ADJ-2026-012',
    created_at: '2026-08-29 16:20:00',
    created_by_name: 'Store Manager John Doe',
    notes: 'Water damaged packaging written off during audit',
  },
  {
    transaction_id: 5006,
    store_id: 1,
    store_name: 'Colombo Station Store',
    product_id: 4,
    product_name: 'Instant Noodles Box (24)',
    sku: 'NDL-BOX-24',
    change_qty: 3000,
    transaction_type: 'receive',
    reference_code: 'TB-095',
    created_at: '2026-08-28 11:15:00',
    created_by_name: 'Operator Silva',
    notes: 'Standard delivery receipt',
  },
  {
    transaction_id: 5007,
    store_id: 1,
    store_name: 'Colombo Station Store',
    product_id: 9,
    product_name: 'Soft Drink Crate (24)',
    sku: 'SFT-DRK-CR24',
    change_qty: -120,
    transaction_type: 'dispatch',
    reference_code: 'DEL-8790',
    created_at: '2026-08-27 15:10:00',
    created_by_name: 'Driver Jayawardena',
    notes: 'Retail Mart replenishment',
  },
  {
    transaction_id: 5008,
    store_id: 1,
    store_name: 'Colombo Station Store',
    product_id: 10,
    product_name: 'Baby Diapers Pack',
    sku: 'BBY-DIA-PCK',
    change_qty: 800,
    transaction_type: 'receive',
    reference_code: 'TB-091',
    created_at: '2026-08-26 14:00:00',
    created_by_name: 'Operator Silva',
    notes: 'Received without remarks',
  },
];
