/**
 * @file mockData.ts
 * @description Realistic seed-compliant mock dataset for Master Data (/admin/master-data).
 * Conforms to Docs/06_seed-data-spec.md, Docs/04_database-schema-v4.md, and UI/master_data/code.html.
 */

import {
  ProductItem,
  RouteItem,
  CityItem,
  EmployeeItem,
  CustomerItem,
  TabStatsConfig,
  MasterDataTab,
} from './types';

/**
 * Baseline Sri Lankan cities (Docs/06_seed-data-spec.md §1).
 */
export const MOCK_CITIES: CityItem[] = [
  { city_id: 1, city_name: 'Kandy', is_origin: true, is_destination: false, store_name: 'Kandy Central Hub', status: 'Active' },
  { city_id: 2, city_name: 'Colombo', is_origin: false, is_destination: true, store_name: 'Colombo Station Store', status: 'Active' },
  { city_id: 3, city_name: 'Negombo', is_origin: false, is_destination: true, store_name: 'Negombo Station Store', status: 'Active' },
  { city_id: 4, city_name: 'Galle', is_origin: false, is_destination: true, store_name: 'Galle Station Store', status: 'Active' },
  { city_id: 5, city_name: 'Matara', is_origin: false, is_destination: true, store_name: 'Matara Station Store', status: 'Active' },
  { city_id: 6, city_name: 'Jaffna', is_origin: false, is_destination: true, store_name: 'Jaffna Station Store', status: 'Active' },
  { city_id: 7, city_name: 'Trincomalee', is_origin: false, is_destination: true, store_name: 'Trincomalee Station Store', status: 'Active' },
];

/**
 * Destination stores list for route and employee assignments (Docs/06_seed-data-spec.md §2).
 */
export const MOCK_STORES = [
  { store_id: 1, store_name: 'Colombo Station Store', city_id: 2, city_name: 'Colombo' },
  { store_id: 2, store_name: 'Negombo Station Store', city_id: 3, city_name: 'Negombo' },
  { store_id: 3, store_name: 'Galle Station Store', city_id: 4, city_name: 'Galle' },
  { store_id: 4, store_name: 'Matara Station Store', city_id: 5, city_name: 'Matara' },
  { store_id: 5, store_name: 'Jaffna Station Store', city_id: 6, city_name: 'Jaffna' },
  { store_id: 6, store_name: 'Trincomalee Station Store', city_id: 7, city_name: 'Trincomalee' },
];

/**
 * Baseline Product Catalog (Docs/06_seed-data-spec.md §3 + UI/master_data/code.html items).
 */
export const INITIAL_PRODUCTS: ProductItem[] = [
  {
    product_id: 1,
    sku: 'PRD-8901',
    product_name: 'Detergent Powder 1kg',
    category: 'Household',
    unit_of_measure: 'box',
    unit_price: 450.00,
    space_rate: 0.50,
    status: 'Active',
    created_at: '2026-08-01',
  },
  {
    product_id: 2,
    sku: 'PRD-8902',
    product_name: 'Dish Soap 500ml',
    category: 'Household',
    unit_of_measure: 'bottle',
    unit_price: 180.00,
    space_rate: 0.20,
    status: 'Active',
    created_at: '2026-08-01',
  },
  {
    product_id: 3,
    sku: 'PRD-8903',
    product_name: 'Biscuits Family Pack',
    category: 'Food',
    unit_of_measure: 'pack',
    unit_price: 220.00,
    space_rate: 0.15,
    status: 'Active',
    created_at: '2026-08-02',
  },
  {
    product_id: 4,
    sku: 'PRD-8904',
    product_name: 'Instant Noodles Box (24)',
    category: 'Food',
    unit_of_measure: 'box',
    unit_price: 1200.00,
    space_rate: 0.80,
    status: 'Low Stock',
    created_at: '2026-08-02',
  },
  {
    product_id: 5,
    sku: 'PRD-8905',
    product_name: 'Tea Powder 400g',
    category: 'Food',
    unit_of_measure: 'pack',
    unit_price: 350.00,
    space_rate: 0.10,
    status: 'Active',
    created_at: '2026-08-03',
  },
  {
    product_id: 6,
    sku: 'PRD-8906',
    product_name: 'Coconut Oil 1L',
    category: 'Food',
    unit_of_measure: 'bottle',
    unit_price: 650.00,
    space_rate: 0.30,
    status: 'Active',
    created_at: '2026-08-03',
  },
  {
    product_id: 7,
    sku: 'PRD-8907',
    product_name: 'Rice 5kg Bag',
    category: 'Food',
    unit_of_measure: 'bag',
    unit_price: 900.00,
    space_rate: 1.00,
    status: 'Active',
    created_at: '2026-08-04',
  },
  {
    product_id: 8,
    sku: 'PRD-8908',
    product_name: 'Toothpaste 100g',
    category: 'Personal Care',
    unit_of_measure: 'tube',
    unit_price: 210.00,
    space_rate: 0.05,
    status: 'Active',
    created_at: '2026-08-04',
  },
  {
    product_id: 9,
    sku: 'PRD-8909',
    product_name: 'Soft Drink Crate (24)',
    category: 'Beverages',
    unit_of_measure: 'crate',
    unit_price: 1800.00,
    space_rate: 1.50,
    status: 'Active',
    created_at: '2026-08-05',
  },
  {
    product_id: 10,
    sku: 'PRD-8910',
    product_name: 'Baby Diapers Pack',
    category: 'Personal Care',
    unit_of_measure: 'pack',
    unit_price: 950.00,
    space_rate: 0.40,
    status: 'Active',
    created_at: '2026-08-05',
  },
  {
    product_id: 11,
    sku: 'PRD-8911',
    product_name: 'Canned Fish 425g Case (24)',
    category: 'Food',
    unit_of_measure: 'case',
    unit_price: 2400.00,
    space_rate: 0.90,
    status: 'Low Stock',
    created_at: '2026-08-06',
  },
  {
    product_id: 12,
    sku: 'PRD-8912',
    product_name: 'Shampoo 400ml',
    category: 'Personal Care',
    unit_of_measure: 'bottle',
    unit_price: 480.00,
    space_rate: 0.15,
    status: 'Inactive',
    created_at: '2026-08-06',
  },
  {
    product_id: 13,
    sku: 'PRD-8913',
    product_name: 'Industrial Pallet Heavy Duty',
    category: 'Logistics Equipment',
    unit_of_measure: 'unit',
    unit_price: 3500.00,
    space_rate: 1.50,
    status: 'Active',
    created_at: '2026-08-10',
  },
  {
    product_id: 14,
    sku: 'PRD-8914',
    product_name: 'Medical Grade Insulated Cooler',
    category: 'Cold Chain',
    unit_of_measure: 'box',
    unit_price: 6800.00,
    space_rate: 0.80,
    status: 'Active',
    created_at: '2026-08-11',
  },
];

/**
 * Baseline Routes with Coverage Areas (Docs/06_seed-data-spec.md §5).
 */
export const INITIAL_ROUTES: RouteItem[] = [
  {
    route_id: 1,
    store_id: 1,
    store_name: 'Colombo Station Store',
    route_name: 'Colombo North Route',
    coverage_description: 'Covers Colombo Fort, Pettah, Maradana, Kotahena, and Grandpass',
    max_delivery_time_hours: 4.0,
    coverage_areas: [
      { coverage_id: 101, route_id: 1, city_id: 2, city_name: 'Colombo', area_name: 'Colombo 01 - Fort' },
      { coverage_id: 102, route_id: 1, city_id: 2, city_name: 'Colombo', area_name: 'Colombo 11 - Pettah' },
      { coverage_id: 103, route_id: 1, city_id: 2, city_name: 'Colombo', area_name: 'Colombo 10 - Maradana' },
      { coverage_id: 104, route_id: 1, city_id: 2, city_name: 'Colombo', area_name: 'Colombo 13 - Kotahena' },
    ],
    status: 'Active',
    created_at: '2026-08-01',
  },
  {
    route_id: 2,
    store_id: 1,
    store_name: 'Colombo Station Store',
    route_name: 'Colombo South Route',
    coverage_description: 'Covers Colombo 03–07, Bambalapitiya, Wellawatte, and Dehiwala',
    max_delivery_time_hours: 5.0,
    coverage_areas: [
      { coverage_id: 105, route_id: 2, city_id: 2, city_name: 'Colombo', area_name: 'Colombo 03 - Kollupitiya' },
      { coverage_id: 106, route_id: 2, city_id: 2, city_name: 'Colombo', area_name: 'Colombo 04 - Bambalapitiya' },
      { coverage_id: 107, route_id: 2, city_id: 2, city_name: 'Colombo', area_name: 'Colombo 06 - Wellawatte' },
      { coverage_id: 108, route_id: 2, city_id: 2, city_name: 'Colombo', area_name: 'Dehiwala Suburb' },
    ],
    status: 'Active',
    created_at: '2026-08-01',
  },
  {
    route_id: 3,
    store_id: 2,
    store_name: 'Negombo Station Store',
    route_name: 'Negombo Coastal Route',
    coverage_description: 'Covers Beach Road, Kudapaduwa, Porutota, and Kochchikade',
    max_delivery_time_hours: 4.5,
    coverage_areas: [
      { coverage_id: 109, route_id: 3, city_id: 3, city_name: 'Negombo', area_name: 'Beach Road Sector' },
      { coverage_id: 110, route_id: 3, city_id: 3, city_name: 'Negombo', area_name: 'Porutota Coastal Strip' },
      { coverage_id: 111, route_id: 3, city_id: 3, city_name: 'Negombo', area_name: 'Kochchikade North' },
    ],
    status: 'Active',
    created_at: '2026-08-02',
  },
  {
    route_id: 4,
    store_id: 2,
    store_name: 'Negombo Station Store',
    route_name: 'Negombo Inland Route',
    coverage_description: 'Covers Kurana, Katunayake Industrial Zone, and Seeduwa',
    max_delivery_time_hours: 4.0,
    coverage_areas: [
      { coverage_id: 112, route_id: 4, city_id: 3, city_name: 'Negombo', area_name: 'Kurana Commercial Hub' },
      { coverage_id: 113, route_id: 4, city_id: 3, city_name: 'Negombo', area_name: 'Katunayake FTZ Corridor' },
      { coverage_id: 114, route_id: 4, city_id: 3, city_name: 'Negombo', area_name: 'Seeduwa South' },
    ],
    status: 'Active',
    created_at: '2026-08-02',
  },
  {
    route_id: 5,
    store_id: 3,
    store_name: 'Galle Station Store',
    route_name: 'Galle Fort & Harbor Route',
    coverage_description: 'Covers Galle Fort Historic District, Port Area, and Main Street',
    max_delivery_time_hours: 3.5,
    coverage_areas: [
      { coverage_id: 115, route_id: 5, city_id: 4, city_name: 'Galle', area_name: 'Galle Fort Heritage Area' },
      { coverage_id: 116, route_id: 5, city_id: 4, city_name: 'Galle', area_name: 'Galle Harbor District' },
      { coverage_id: 117, route_id: 5, city_id: 4, city_name: 'Galle', area_name: 'Main Street Commercial' },
    ],
    status: 'Active',
    created_at: '2026-08-03',
  },
  {
    route_id: 6,
    store_id: 3,
    store_name: 'Galle Station Store',
    route_name: 'Galle Suburbs & Coastal Route',
    coverage_description: 'Covers Unawatuna, Karapitiya Hospital area, and Richmond Hill',
    max_delivery_time_hours: 5.0,
    coverage_areas: [
      { coverage_id: 118, route_id: 6, city_id: 4, city_name: 'Galle', area_name: 'Karapitiya Medical Zone' },
      { coverage_id: 119, route_id: 6, city_id: 4, city_name: 'Galle', area_name: 'Unawatuna South' },
      { coverage_id: 120, route_id: 6, city_id: 4, city_name: 'Galle', area_name: 'Richmond Hill' },
    ],
    status: 'Active',
    created_at: '2026-08-03',
  },
  {
    route_id: 7,
    store_id: 4,
    store_name: 'Matara Station Store',
    route_name: 'Matara Central Route',
    coverage_description: 'Covers Nupe, Fort Matara, Beach Road, and Commercial Core',
    max_delivery_time_hours: 4.0,
    coverage_areas: [
      { coverage_id: 121, route_id: 7, city_id: 5, city_name: 'Matara', area_name: 'Matara Town Center' },
      { coverage_id: 122, route_id: 7, city_id: 5, city_name: 'Matara', area_name: 'Nupe Junction' },
      { coverage_id: 123, route_id: 7, city_id: 5, city_name: 'Matara', area_name: 'Matara Fort Sector' },
    ],
    status: 'Active',
    created_at: '2026-08-04',
  },
  {
    route_id: 8,
    store_id: 4,
    store_name: 'Matara Station Store',
    route_name: 'Matara Coastal & Suburbs Route',
    coverage_description: 'Covers Dondra, Meddawatta, and Dickwella corridor',
    max_delivery_time_hours: 6.0,
    coverage_areas: [
      { coverage_id: 124, route_id: 8, city_id: 5, city_name: 'Matara', area_name: 'Dondra Lighthouse Corridor' },
      { coverage_id: 125, route_id: 8, city_id: 5, city_name: 'Matara', area_name: 'Meddawatta Outer' },
    ],
    status: 'Active',
    created_at: '2026-08-04',
  },
  {
    route_id: 9,
    store_id: 5,
    store_name: 'Jaffna Station Store',
    route_name: 'Jaffna Town Central Route',
    coverage_description: 'Covers Hospital Road, Main Street, Nallur, and Chundikuli',
    max_delivery_time_hours: 4.0,
    coverage_areas: [
      { coverage_id: 126, route_id: 9, city_id: 6, city_name: 'Jaffna', area_name: 'Hospital Road Corridor' },
      { coverage_id: 127, route_id: 9, city_id: 6, city_name: 'Jaffna', area_name: 'Nallur Temple Sector' },
      { coverage_id: 128, route_id: 9, city_id: 6, city_name: 'Jaffna', area_name: 'Chundikuli' },
    ],
    status: 'Active',
    created_at: '2026-08-05',
  },
  {
    route_id: 10,
    store_id: 5,
    store_name: 'Jaffna Station Store',
    route_name: 'Jaffna Peninsula Route',
    coverage_description: 'Covers Chavakachcheri, Kopay, and Point Pedro Road',
    max_delivery_time_hours: 6.5,
    coverage_areas: [
      { coverage_id: 129, route_id: 10, city_id: 6, city_name: 'Jaffna', area_name: 'Kopay East' },
      { coverage_id: 130, route_id: 10, city_id: 6, city_name: 'Jaffna', area_name: 'Chavakachcheri Town' },
      { coverage_id: 131, route_id: 10, city_id: 6, city_name: 'Jaffna', area_name: 'Point Pedro Junction' },
    ],
    status: 'Active',
    created_at: '2026-08-05',
  },
  {
    route_id: 11,
    store_id: 6,
    store_name: 'Trincomalee Station Store',
    route_name: 'Trincomalee Bay Route',
    coverage_description: 'Covers Dockyard Road, Harbor Area, Fort Frederick, and Town Center',
    max_delivery_time_hours: 3.5,
    coverage_areas: [
      { coverage_id: 132, route_id: 11, city_id: 7, city_name: 'Trincomalee', area_name: 'Dockyard Marine Corridor' },
      { coverage_id: 133, route_id: 11, city_id: 7, city_name: 'Trincomalee', area_name: 'Fort Frederick Sector' },
      { coverage_id: 134, route_id: 11, city_id: 7, city_name: 'Trincomalee', area_name: 'Town Commercial Center' },
    ],
    status: 'Active',
    created_at: '2026-08-06',
  },
  {
    route_id: 12,
    store_id: 6,
    store_name: 'Trincomalee Station Store',
    route_name: 'Trincomalee Coastal & Suburbs Route',
    coverage_description: 'Covers Uppuveli, Nilaveli, and China Bay Industrial Zone',
    max_delivery_time_hours: 5.5,
    coverage_areas: [
      { coverage_id: 135, route_id: 12, city_id: 7, city_name: 'Trincomalee', area_name: 'Uppuveli Tourist Strip' },
      { coverage_id: 136, route_id: 12, city_id: 7, city_name: 'Trincomalee', area_name: 'China Bay Industrial' },
      { coverage_id: 137, route_id: 12, city_id: 7, city_name: 'Trincomalee', area_name: 'Nilaveli Coastal' },
    ],
    status: 'Active',
    created_at: '2026-08-06',
  },
];

/**
 * Baseline Employees (Docs/06_seed-data-spec.md §6).
 */
export const INITIAL_EMPLOYEES: EmployeeItem[] = [
  {
    employee_id: 1,
    full_name: 'Kavinda Perera',
    nic_number: '198421004512',
    phone: '077-1234567',
    email: 'k.perera@kandypack.lk',
    employee_type: 'system_administrator',
    employee_type_label: 'System Administrator',
    home_store_id: null,
    home_store_name: 'Central HQ (Kandy)',
    status: 'Active',
    hire_date: '2023-01-15',
  },
  {
    employee_id: 2,
    full_name: 'Sarah Jenkins',
    nic_number: '198854002341',
    phone: '071-8899221',
    email: 's.jenkins@kandypack.lk',
    employee_type: 'logistics_manager',
    employee_type_label: 'Logistics Manager',
    home_store_id: null,
    home_store_name: 'Central HQ (Kandy)',
    status: 'Active',
    hire_date: '2023-03-10',
  },
  {
    employee_id: 3,
    full_name: 'Malik Jayawardena',
    nic_number: '199014003299',
    phone: '072-4455667',
    email: 'm.jayawardena@kandypack.lk',
    employee_type: 'logistics_manager',
    employee_type_label: 'Logistics Manager',
    home_store_id: null,
    home_store_name: 'Central HQ (Kandy)',
    status: 'Active',
    hire_date: '2023-04-01',
  },
  {
    employee_id: 4,
    full_name: 'Sunil Weerasinghe',
    nic_number: '198211009844',
    phone: '077-9911223',
    email: 's.weerasinghe@kandypack.lk',
    employee_type: 'store_manager',
    employee_type_label: 'Store Manager',
    home_store_id: 1,
    home_store_name: 'Colombo Station Store',
    status: 'Active',
    hire_date: '2023-02-01',
  },
  {
    employee_id: 5,
    full_name: 'Nihal Fernando',
    nic_number: '198532007712',
    phone: '076-2233445',
    email: 'n.fernando@kandypack.lk',
    employee_type: 'store_manager',
    employee_type_label: 'Store Manager',
    home_store_id: 2,
    home_store_name: 'Negombo Station Store',
    status: 'Active',
    hire_date: '2023-02-15',
  },
  {
    employee_id: 6,
    full_name: 'Chaminda Silva',
    nic_number: '198715008922',
    phone: '070-5566778',
    email: 'c.silva@kandypack.lk',
    employee_type: 'store_manager',
    employee_type_label: 'Store Manager',
    home_store_id: 3,
    home_store_name: 'Galle Station Store',
    status: 'Active',
    hire_date: '2023-03-01',
  },
  {
    employee_id: 7,
    full_name: 'Priyantha Gunasekara',
    nic_number: '198644005511',
    phone: '071-7788990',
    email: 'p.gunasekara@kandypack.lk',
    employee_type: 'store_manager',
    employee_type_label: 'Store Manager',
    home_store_id: 4,
    home_store_name: 'Matara Station Store',
    status: 'Active',
    hire_date: '2023-03-15',
  },
  {
    employee_id: 8,
    full_name: 'Tharindu Rathnayake',
    nic_number: '199212001188',
    phone: '077-3344556',
    email: 't.rathnayake@kandypack.lk',
    employee_type: 'driver',
    employee_type_label: 'Driver',
    home_store_id: 1,
    home_store_name: 'Colombo Station Store',
    license_number: 'B-8839201',
    license_expiry: '2028-04-30',
    status: 'Active',
    hire_date: '2023-05-10',
  },
  {
    employee_id: 9,
    full_name: 'Kasun Bandara',
    nic_number: '199416003322',
    phone: '078-1122334',
    email: 'k.bandara@kandypack.lk',
    employee_type: 'driver',
    employee_type_label: 'Driver',
    home_store_id: 1,
    home_store_name: 'Colombo Station Store',
    license_number: 'B-7749102',
    license_expiry: '2028-06-15',
    status: 'Active',
    hire_date: '2023-05-15',
  },
  {
    employee_id: 10,
    full_name: 'Dinesh Wickramasinghe',
    nic_number: '199518002244',
    phone: '075-9988776',
    email: 'd.wickrama@kandypack.lk',
    employee_type: 'assistant',
    employee_type_label: 'Assistant',
    home_store_id: 1,
    home_store_name: 'Colombo Station Store',
    status: 'Active',
    hire_date: '2023-06-01',
  },
  {
    employee_id: 11,
    full_name: 'Roshan Abeywickrama',
    nic_number: '199320005566',
    phone: '071-4433221',
    email: 'r.abeywickrama@kandypack.lk',
    employee_type: 'assistant',
    employee_type_label: 'Assistant',
    home_store_id: 2,
    home_store_name: 'Negombo Station Store',
    status: 'Active',
    hire_date: '2023-06-15',
  },
  {
    employee_id: 12,
    full_name: 'Anura Senanayake',
    nic_number: '198909004433',
    phone: '076-8877665',
    email: 'a.senanayake@kandypack.lk',
    employee_type: 'driver',
    employee_type_label: 'Driver',
    home_store_id: 3,
    home_store_name: 'Galle Station Store',
    license_number: 'B-5532109',
    license_expiry: '2028-08-20',
    status: 'On Leave',
    hire_date: '2023-07-01',
  },
];

/**
 * Baseline Customers (Docs/06_seed-data-spec.md §4: 4 per destination city = 24 rows).
 */
export const INITIAL_CUSTOMERS: CustomerItem[] = [
  // Colombo
  {
    customer_id: 1,
    customer_name: 'Colombo Retail Mart',
    customer_type: 'retail',
    phone: '077-2233111',
    email: 'colombo.mart@retailmail.lk',
    registered_city_id: 2,
    registered_city_name: 'Colombo',
    address_line: 'No. 45, Main Street, Pettah, Colombo 11',
    status: 'Active',
    created_at: '2026-08-01',
  },
  {
    customer_id: 2,
    customer_name: 'Colombo Family Store',
    customer_type: 'retail',
    phone: '071-3344222',
    email: 'familystore.cmb@gmail.com',
    registered_city_id: 2,
    registered_city_name: 'Colombo',
    address_line: 'No. 120, Galle Road, Bambalapitiya, Colombo 04',
    status: 'Active',
    created_at: '2026-08-01',
  },
  {
    customer_id: 3,
    customer_name: 'Colombo Wholesale Distributors',
    customer_type: 'wholesale',
    phone: '011-2345678',
    email: 'orders@colombowholesale.lk',
    registered_city_id: 2,
    registered_city_name: 'Colombo',
    address_line: 'Plot 8B, Industrial Zone, Grandpass, Colombo 14',
    status: 'Active',
    created_at: '2026-08-02',
  },
  {
    customer_id: 4,
    customer_name: 'Colombo Trading Co.',
    customer_type: 'wholesale',
    phone: '011-4567890',
    email: 'trade@cmbtrading.com',
    registered_city_id: 2,
    registered_city_name: 'Colombo',
    address_line: 'No. 310, Maradana Road, Colombo 10',
    status: 'Active',
    created_at: '2026-08-02',
  },
  // Negombo
  {
    customer_id: 5,
    customer_name: 'Negombo Retail Mart',
    customer_type: 'retail',
    phone: '077-4455333',
    email: 'negombo.mart@gmail.com',
    registered_city_id: 3,
    registered_city_name: 'Negombo',
    address_line: 'No. 78, Sea Street, Negombo',
    status: 'Active',
    created_at: '2026-08-03',
  },
  {
    customer_id: 6,
    customer_name: 'Negombo Family Store',
    customer_type: 'retail',
    phone: '071-5566444',
    email: 'negombofamily@gmail.com',
    registered_city_id: 3,
    registered_city_name: 'Negombo',
    address_line: 'No. 14, Colombo Road, Kurana, Negombo',
    status: 'Active',
    created_at: '2026-08-03',
  },
  {
    customer_id: 7,
    customer_name: 'Negombo Wholesale Distributors',
    customer_type: 'wholesale',
    phone: '031-2223344',
    email: 'sales@negombowholesale.lk',
    registered_city_id: 3,
    registered_city_name: 'Negombo',
    address_line: 'No. 200, Main Street, Kochchikade, Negombo',
    status: 'Active',
    created_at: '2026-08-04',
  },
  {
    customer_id: 8,
    customer_name: 'Negombo Trading Co.',
    customer_type: 'wholesale',
    phone: '031-4445566',
    email: 'info@negombotrading.lk',
    registered_city_id: 3,
    registered_city_name: 'Negombo',
    address_line: 'No. 88, Katunayake Airport Road, Seeduwa',
    status: 'Active',
    created_at: '2026-08-04',
  },
  // Galle
  {
    customer_id: 9,
    customer_name: 'Galle Retail Mart',
    customer_type: 'retail',
    phone: '077-6677555',
    email: 'gallemart@gmail.com',
    registered_city_id: 4,
    registered_city_name: 'Galle',
    address_line: 'No. 52, Church Street, Galle Fort',
    status: 'Active',
    created_at: '2026-08-05',
  },
  {
    customer_id: 10,
    customer_name: 'Galle Family Store',
    customer_type: 'retail',
    phone: '071-7788666',
    email: 'gallefamily@gmail.com',
    registered_city_id: 4,
    registered_city_name: 'Galle',
    address_line: 'No. 110, Matara Road, Karapitiya, Galle',
    status: 'Active',
    created_at: '2026-08-05',
  },
  {
    customer_id: 11,
    customer_name: 'Galle Wholesale Distributors',
    customer_type: 'wholesale',
    phone: '091-2234567',
    email: 'galle.wholesale@lknet.lk',
    registered_city_id: 4,
    registered_city_name: 'Galle',
    address_line: 'No. 15, Harbor Access Road, Galle Port',
    status: 'Active',
    created_at: '2026-08-06',
  },
  {
    customer_id: 12,
    customer_name: 'Galle Trading Co.',
    customer_type: 'wholesale',
    phone: '091-3345678',
    email: 'trading@galletraders.lk',
    registered_city_id: 4,
    registered_city_name: 'Galle',
    address_line: 'No. 95, Colombo Road, Gintota, Galle',
    status: 'Active',
    created_at: '2026-08-06',
  },
  // Matara
  {
    customer_id: 13,
    customer_name: 'Matara Retail Mart',
    customer_type: 'retail',
    phone: '077-8899666',
    email: 'matara.mart@gmail.com',
    registered_city_id: 5,
    registered_city_name: 'Matara',
    address_line: 'No. 24, Anagarika Dharmapala Mawatha, Matara',
    status: 'Active',
    created_at: '2026-08-07',
  },
  {
    customer_id: 14,
    customer_name: 'Matara Family Store',
    customer_type: 'retail',
    phone: '071-9900777',
    email: 'matarafamily@gmail.com',
    registered_city_id: 5,
    registered_city_name: 'Matara',
    address_line: 'No. 89, Beach Road, Nupe, Matara',
    status: 'Active',
    created_at: '2026-08-07',
  },
  {
    customer_id: 15,
    customer_name: 'Matara Wholesale Distributors',
    customer_type: 'wholesale',
    phone: '041-2223388',
    email: 'info@matarawholesale.lk',
    registered_city_id: 5,
    registered_city_name: 'Matara',
    address_line: 'No. 140, Tangalle Road, Meddawatta, Matara',
    status: 'Active',
    created_at: '2026-08-08',
  },
  {
    customer_id: 16,
    customer_name: 'Matara Trading Co.',
    customer_type: 'wholesale',
    phone: '041-3334499',
    email: 'matara.trading@lknet.lk',
    registered_city_id: 5,
    registered_city_name: 'Matara',
    address_line: 'No. 62, Station Road, Fort, Matara',
    status: 'Active',
    created_at: '2026-08-08',
  },
  // Jaffna
  {
    customer_id: 17,
    customer_name: 'Jaffna Retail Mart',
    customer_type: 'retail',
    phone: '077-1133555',
    email: 'jaffna.mart@gmail.com',
    registered_city_id: 6,
    registered_city_name: 'Jaffna',
    address_line: 'No. 320, Hospital Road, Jaffna',
    status: 'Active',
    created_at: '2026-08-09',
  },
  {
    customer_id: 18,
    customer_name: 'Jaffna Family Store',
    customer_type: 'retail',
    phone: '071-2244666',
    email: 'jaffnafamily@gmail.com',
    registered_city_id: 6,
    registered_city_name: 'Jaffna',
    address_line: 'No. 75, Point Pedro Road, Nallur, Jaffna',
    status: 'Active',
    created_at: '2026-08-09',
  },
  {
    customer_id: 19,
    customer_name: 'Jaffna Wholesale Distributors',
    customer_type: 'wholesale',
    phone: '021-2223399',
    email: 'orders@jaffnawholesale.lk',
    registered_city_id: 6,
    registered_city_name: 'Jaffna',
    address_line: 'No. 405, Kandy Road, Chavakachcheri, Jaffna',
    status: 'Active',
    created_at: '2026-08-10',
  },
  {
    customer_id: 20,
    customer_name: 'Jaffna Trading Co.',
    customer_type: 'wholesale',
    phone: '021-3334400',
    email: 'trade@jaffnatrading.lk',
    registered_city_id: 6,
    registered_city_name: 'Jaffna',
    address_line: 'No. 18, Main Street, Jaffna Town',
    status: 'Active',
    created_at: '2026-08-10',
  },
  // Trincomalee
  {
    customer_id: 21,
    customer_name: 'Trincomalee Retail Mart',
    customer_type: 'retail',
    phone: '077-3355777',
    email: 'trinco.mart@gmail.com',
    registered_city_id: 7,
    registered_city_name: 'Trincomalee',
    address_line: 'No. 44, Dockyard Road, Trincomalee',
    status: 'Active',
    created_at: '2026-08-11',
  },
  {
    customer_id: 22,
    customer_name: 'Trincomalee Family Store',
    customer_type: 'retail',
    phone: '071-4466888',
    email: 'trincofamily@gmail.com',
    registered_city_id: 7,
    registered_city_name: 'Trincomalee',
    address_line: 'No. 12, Inner Harbor Road, Trincomalee',
    status: 'Active',
    created_at: '2026-08-11',
  },
  {
    customer_id: 23,
    customer_name: 'Trincomalee Wholesale Distributors',
    customer_type: 'wholesale',
    phone: '026-2223311',
    email: 'sales@trincowholesale.lk',
    registered_city_id: 7,
    registered_city_name: 'Trincomalee',
    address_line: 'Plot 3, China Bay Industrial Area, Trincomalee',
    status: 'Active',
    created_at: '2026-08-12',
  },
  {
    customer_id: 24,
    customer_name: 'Trincomalee Trading Co.',
    customer_type: 'wholesale',
    phone: '026-3334422',
    email: 'trade@trincotrading.lk',
    registered_city_id: 7,
    registered_city_name: 'Trincomalee',
    address_line: 'No. 88, Uppuveli Main Road, Trincomalee',
    status: 'Active',
    created_at: '2026-08-12',
  },
];

/**
 * Derives the dynamic 3-metric statistics cards for the active tab.
 *
 * @param tab The current active master data tab
 * @param products Current list of products
 * @param routes Current list of routes
 * @param cities Current list of cities
 * @param employees Current list of employees
 * @param customers Current list of customers
 * @returns TabStatsConfig containing stat1, stat2, and stat3
 */
export function getStatsForTab(
  tab: MasterDataTab,
  products: ProductItem[],
  routes: RouteItem[],
  cities: CityItem[],
  employees: EmployeeItem[],
  customers: CustomerItem[]
): TabStatsConfig {
  switch (tab) {
    case 'products': {
      const activeCount = products.filter((p) => p.status === 'Active').length;
      const categories = new Set(products.map((p) => p.category)).size;
      return {
        stat1: {
          title: 'Total Products',
          value: products.length,
          theme: 'purple',
          icon: 'inventory',
        },
        stat2: {
          title: 'Active SKU',
          value: activeCount,
          theme: 'green',
          icon: 'check_circle',
        },
        stat3: {
          title: 'Categories',
          value: categories,
          theme: 'blue',
          icon: 'category',
        },
      };
    }
    case 'routes': {
      const activeRoutes = routes.filter((r) => r.status === 'Active').length;
      const uniqueStores = new Set(routes.map((r) => r.store_id)).size;
      return {
        stat1: {
          title: 'Total Routes',
          value: routes.length,
          theme: 'purple',
          icon: 'alt_route',
        },
        stat2: {
          title: 'Active Routes',
          value: activeRoutes,
          theme: 'green',
          icon: 'verified',
        },
        stat3: {
          title: 'Stores & Hubs',
          value: uniqueStores,
          theme: 'blue',
          icon: 'store',
        },
      };
    }
    case 'cities': {
      const originCount = cities.filter((c) => c.is_origin).length;
      const destCount = cities.filter((c) => c.is_destination).length;
      return {
        stat1: {
          title: 'Total Cities',
          value: cities.length,
          theme: 'purple',
          icon: 'location_city',
        },
        stat2: {
          title: 'Origin Hub (Kandy)',
          value: originCount,
          theme: 'green',
          icon: 'train',
        },
        stat3: {
          title: 'Destination Stations',
          value: destCount,
          theme: 'blue',
          icon: 'warehouse',
        },
      };
    }
    case 'employees': {
      const activeStaff = employees.filter((e) => e.status === 'Active').length;
      const driverAssistantCount = employees.filter(
        (e) => e.employee_type === 'driver' || e.employee_type === 'assistant'
      ).length;
      return {
        stat1: {
          title: 'Total Employees',
          value: employees.length,
          theme: 'purple',
          icon: 'group',
        },
        stat2: {
          title: 'Active Staff',
          value: activeStaff,
          theme: 'green',
          icon: 'badge',
        },
        stat3: {
          title: 'Drivers & Assistants',
          value: driverAssistantCount,
          theme: 'blue',
          icon: 'local_shipping',
        },
      };
    }
    case 'customers': {
      const retailCount = customers.filter((c) => c.customer_type === 'retail').length;
      const wholesaleCount = customers.filter((c) => c.customer_type === 'wholesale').length;
      return {
        stat1: {
          title: 'Total Customers',
          value: customers.length,
          theme: 'purple',
          icon: 'storefront',
        },
        stat2: {
          title: 'Retail Accounts',
          value: retailCount,
          theme: 'green',
          icon: 'shopping_bag',
        },
        stat3: {
          title: 'Wholesale Distributors',
          value: wholesaleCount,
          theme: 'blue',
          icon: 'domain',
        },
      };
    }
  }
}
